# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!This is TechPledge
  displayName: 'Run a one-line script'

- script: |
    echo Welcome to TechPledge Consulting Service Azure DevOps Training
    echo See http://Techpledgeconsulting.com
  displayName: 'Run a multi-line script'
